### ISSUE TITLE
Minecraft freezes on startup

### ISSUE THREAD

**Issue by MelanX** [gigaherz/JsonThings#8] opened 2022-08-30 18:03 UTC
Related to https://github.com/MelanX/CaveStone/issues/2
For some more information, look there.
tl;dr: Game launches with Forge 43.0.8 and JsonThings 0.6.0 but stops randomly with white screen.

To reproduce, I trimmed down my pack. My pack only contains the mod itself and this as thingpack: 
[thingpacks.zip](https://github.com/gigaherz/JsonThings/files/9455444/thingpacks.zip)

latest.log:
https://gist.github.com/MelanX/7e62249c117ae4e2118198150728de86

**Comment by gigaherz** [comment] 2022-08-30 18:07
Err, when does the freeze happen?

**Comment by MelanX** [comment] 2022-08-30 18:18
In the debug log, the latest entry is `[Render thread/DEBUG] [net.minecraftforge.fml.DeferredWorkQueue/LOADING]: Synchronous work queue completed in 132.5 ms`. When only looking at the game window, it happens before the red background with white logo and the loading bar is loaded.

**Comment by gigaherz** [comment] 2022-08-30 18:32
Have you tried with a newer forge version? I can't reproduce the issue in 43.1.3

**Comment by MelanX** [comment] 2022-08-30 19:00
Yes, on the third try I was able to reproduce it with 43.1.3. I'll try tomorrow with a fresh install. Maybe some "old" data (which shouldn't be loaded if the mods aren't present to load the config) interferes it.

**Comment by MelanX** [comment] 2022-09-02 17:48
Sorry for the delay. I now created a new profile in CurseForge launcher with only JsonThings and Forge 43.1.3. Here you can find the export for the pack.
[jsonthings-test.zip](https://github.com/gigaherz/JsonThings/files/9480074/jsonthings-test.zip)

I was able to reproduce it on the 3. startup.

**Comment by gigaherz** [comment] 2022-09-02 17:50
The fact it takes more than one startup smells horribly of race condition.

**Comment by MelanX** [comment] 2022-09-02 18:06
If there's anything I can do to help you/make finding the problem easier, tell me.

**Comment by gigaherz** [comment] 2022-09-02 18:09
A thread dump when it's stuck would be awesome.

**Comment by MelanX** [comment] 2022-09-02 19:10
Sorry, needed to find out how to correctly generate it. Here you have it: https://gist.github.com/MelanX/4009ca7c1201d0804a608e8c1c1a4d2a

**Comment by gigaherz** [comment] 2022-09-03 19:39
I have worked on a potential solution which will either fix all the issues, or cause even more deadlocks.
Hopefully the former.

I have marked it as alpha until it has gotten some testing. https://www.curseforge.com/minecraft/mc-mods/json-things/files/3965805

**Comment by MelanX** [comment] 2022-09-04 13:53
I tried to trigger it at least 10 times now. It didn't happen again. I'd say that it's fixed.

**Comment by gigaherz** [comment] 2022-09-04 16:09
Awesome!

**Closed by gigaherz** 2022-09-04 16:09 UTC
